// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjdkgkkkjwyrzsmzmjhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqZGtna2trand5cnpzbXptamhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzc4MTYsImV4cCI6MjA3MDYxMzgxNn0.yFzDTZ74k4BiNkAkba5fefn9n57Ibrpd6WAGHL_XNWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});